### ISSUE TITLE
Clean_code_self_assessment

### ISSUE THREAD

**Issue by CobbyElsonfx** [CobbyElsonfx/To-Do-List-App#4]
Congratulations you have done well implement all rules and regulations regarding best practices , but there still some changes you need to work on in order make your project very professional

- [x] Try using const and let more often and when necessary than var keyword in variable declaration
- [x] You may add inline comments to make your project more readable

Generally: 
* Good JavaScript best practices
* Followed the DRY,KISS and YAGNI principles
* Followed HTML and CSS best practices

**Comment by thasipablo** [comment]
Hi @CobbyElsonfx ,
I went through your code and I was impressed by the quality of the code you wrote 👍 .
- [x] Good JavaScript best practices
- [x] Followed the DRY,KISS and YAGNI principles
- [x] Followed HTML and CSS best practices
